### PR TITLE
Make GraalVM native image work

### LINKED ISSUE #8: Get Native Build Passing
Build currently fails now with a native exception.

### PR DESCRIPTION
**Pull request by luneo7**
Fix #8

This PR is actually adding:
1 - `update-netty-substitutions.sh`
2 - `deleteMethod.sh`
3 - `extension/deployment/src/main/java/io/quarkiverse/temporal/deployment/TemporalNativeProcessor.java`

Update netty substitutions fetches Quarkus code and copies Netty and GRPC substitutions and native image configs and changes the targeting to the shaded Netty, that makes Netty and GRPC in the shaded lib work

TemporalNativeProcessor in the other hand handles missing pieces for native build, indexes temporal and nexusrpc libs so we are to use Quarkus Jandex index, it also registers dynamic proxies that Temporal creates during runtime, and takes care of two extra configurations needed for Netty.

The `update-netty-substitutions.sh` execution brings the following paths/files from Quarkus repo with renaming:
1 - `extension/deployment/src/main/java/io/quarkiverse/temporal/deployment/grpchandling`
2 - `extension/deployment/src/main/java/io/quarkiverse/temporal/deployment/nettyhandling`
3 - `extension/runtime/src/main/java/io/quarkiverse/temporal/grpchandling/runtime/graal`
4 - `extension/runtime/src/main/java/io/quarkiverse/temporal/nettyhandling`

Fixes https://github.com/quarkiverse/quarkus-temporal/issues/8

### CODE REVIEW

**Comment by melloware** [comment]
@luneo7 this is great. Can you do me a favor and move all your generated code in both runtime and deployment to `graal` subpaackage so I know all this code is for graal only and generated?

**Deployment:**
`io.quarkiverse.temporal.deployment.graal`

and 

**Runtime:**
`io.quarkiverse.temporal.graal`

File: update-netty-substitutions.sh [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+DEST_GRPC_RUNTIME="extension/runtime/src/main/java/io/quarkiverse/temporal/grpchandling"
+
+SRC_NETTY_DEPLOYMENT="quarkus/extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment"
+SRC_GRPC_DEPLOYMENT="quarkus/extensions/grpc-common/deployment/src/main/java/io/quarkus/grpc/common/deployment"
+
+DEST_NETTY_DEPLOYMENT="extension/deployment/src/main/java/io/quarkiverse/temporal/deployment/nettyhandling"
+DEST_GRPC_DEPLOYMENT="extension/deployment/src/main/java/io/quarkiverse/temporal/deployment/grpchandling"
+
+# When bumping temporal we need to check if netty was updated and match with Quarkus version
+QUARKUS_VERSION=3.16.3
```
Comment (melloware) [inline update-netty-substitutions.sh:17]: Should this be 3.15.4 to match the current Extension version?

File: update-netty-substitutions.sh [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+SRC_GRPC_RUNTIME="quarkus/extensions/grpc-common/runtime/src/main/java/io/quarkus/grpc/common"
+
+DEST_NETTY_RUNTIME="extension/runtime/src/main/java/io/quarkiverse/temporal/nettyhandling"
+DEST_GRPC_RUNTIME="extension/runtime/src/main/java/io/quarkiverse/temporal/grpchandling"
+
+SRC_NETTY_DEPLOYMENT="quarkus/extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment"
+SRC_GRPC_DEPLOYMENT="quarkus/extensions/grpc-common/deployment/src/main/java/io/quarkus/grpc/common/deployment"
+
+DEST_NETTY_DEPLOYMENT="extension/deployment/src/main/java/io/quarkiverse/temporal/deployment/nettyhandling"
+DEST_GRPC_DEPLOYMENT="extension/deployment/src/main/java/io/quarkiverse/temporal/deployment/grpchandling"
```
Comment (melloware) [inline update-netty-substitutions.sh:14]:
```suggestion
DEST_GRPC_DEPLOYMENT="extension/deployment/src/main/java/io/quarkiverse/temporal/deployment/graal/grpchandling"
```

File: update-netty-substitutions.sh [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+SRC_NETTY_RUNTIME="quarkus/extensions/netty/runtime/src/main/java/io/quarkus/netty"
+SRC_GRPC_RUNTIME="quarkus/extensions/grpc-common/runtime/src/main/java/io/quarkus/grpc/common"
+
+DEST_NETTY_RUNTIME="extension/runtime/src/main/java/io/quarkiverse/temporal/nettyhandling"
+DEST_GRPC_RUNTIME="extension/runtime/src/main/java/io/quarkiverse/temporal/grpchandling"
+
+SRC_NETTY_DEPLOYMENT="quarkus/extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment"
+SRC_GRPC_DEPLOYMENT="quarkus/extensions/grpc-common/deployment/src/main/java/io/quarkus/grpc/common/deployment"
+
+DEST_NETTY_DEPLOYMENT="extension/deployment/src/main/java/io/quarkiverse/temporal/deployment/nettyhandling"
```
Comment (melloware) [inline update-netty-substitutions.sh:13]:
```suggestion
DEST_NETTY_DEPLOYMENT="extension/deployment/src/main/java/io/quarkiverse/temporal/deployment/graal/nettyhandling"
```

File: update-netty-substitutions.sh [hunk 4]
```diff
@@ -0,0 +1,120 @@
+#!/bin/bash
+
+# Set directories as variables
+SRC_NETTY_RUNTIME="quarkus/extensions/netty/runtime/src/main/java/io/quarkus/netty"
+SRC_GRPC_RUNTIME="quarkus/extensions/grpc-common/runtime/src/main/java/io/quarkus/grpc/common"
+
+DEST_NETTY_RUNTIME="extension/runtime/src/main/java/io/quarkiverse/temporal/nettyhandling"
+DEST_GRPC_RUNTIME="extension/runtime/src/main/java/io/quarkiverse/temporal/grpchandling"
```
Comment (melloware) [inline update-netty-substitutions.sh:8]:
```suggestion
DEST_GRPC_RUNTIME="extension/runtime/src/main/java/io/quarkiverse/temporal/graal/grpchandling"
```

File: update-netty-substitutions.sh [hunk 5]
```diff
@@ -0,0 +1,120 @@
+#!/bin/bash
+
+# Set directories as variables
+SRC_NETTY_RUNTIME="quarkus/extensions/netty/runtime/src/main/java/io/quarkus/netty"
+SRC_GRPC_RUNTIME="quarkus/extensions/grpc-common/runtime/src/main/java/io/quarkus/grpc/common"
+
+DEST_NETTY_RUNTIME="extension/runtime/src/main/java/io/quarkiverse/temporal/nettyhandling"
```
Comment (melloware) [inline update-netty-substitutions.sh:7]:
```suggestion
DEST_NETTY_RUNTIME="extension/runtime/src/main/java/io/quarkiverse/temporal/graal/nettyhandling"
```

**Review by melloware — CHANGES_REQUESTED** [review]

File: update-netty-substitutions.sh (hunk 1 above)
Comment (luneo7) [reply update-netty-substitutions.sh:17]: Nope, as 3.15.4 uses Netty 4.1.118.Final and there we have changes and substitutions for `ResumptionController` which doesn't exist in the netty shaded version, wish they could match...

Comment (luneo7) [reply update-netty-substitutions.sh:17]: And now we might have an issue with it... as `3.15.4` uses GRPC java 1.65.1 that uses a really old netty version... Quarkus 3.18... 3.19 uses GRPC java 1.69.1... so when we tested we weren't using Quarkus 3.15... the substitutions won't work... so we might need a release targeting 3.15, and another release targeting newer Quarkus versions... as if we fix for 3.15, 3.19 won't work

Comment (luneo7) [reply update-netty-substitutions.sh:17]: So for Quarkus 3.15 we would need to target quarkus version `3.12.3` for substitutions, and for newer Quarkus `3.16.3` as those versions matches the shaded netty classes

Comment (melloware) [reply update-netty-substitutions.sh:17]: no should we move right to 3.19.3 then?

**Comment by melloware** [comment]
I made a 315-LTS branch just so we have a branch in case that was off the last release 0.17 so I think we are fine to move Main to 3.19.3.

File: update-netty-substitutions.sh (hunk 1 above)
Comment (melloware) [reply update-netty-substitutions.sh:17]: yep lets move forward with 3.19 and not worry about 3.15

**Comment by melloware** [comment]
All native tests pass!  you are a hero @luneo7

**Comment by melloware** [comment]
0.1.0 is now in Maven Central!

**Comment by melloware** [comment]
@luneo7 you should STAR this repo.  The more stars we get the better.

**Comment by luneo7** [comment]
Just starred it. Saw that you added macOS build as well, Mandrel also distributes builds for it, we don't need to use Liberica there.

**Comment by melloware** [comment]
Ok can you submit a PR I have only ever gotten MacOs to work this way?

**Comment by melloware** [comment]
@luneo7 when we tried on JasperReports to automate Native builds on MacOS it only worked with Liberica. Maybe that has changed?

**Comment by luneo7** [comment]
@melloware yeah, before GH had only macos x86 runners and mandrel has aarch64 only macos distribution, right now GH macos runners (since macos v14) are defaulted to aarch64 so it works now =)

**Comment by melloware** [comment]
Just updated and it passed!
